### PR TITLE
Update configs for rev05 run

### PR DESCRIPTION
**Pull request by jrs65**
- config(daily): restore refactored second round RFI excision
- config(daily): write large outputs in zarr format

### CODE REVIEW

**Comment by jrs65** [comment]
@ljgray I think this config with the last releases of all the branches should be what we want to run.

**Comment by ljgray** [comment]
Just curious, what is the rationale for using the zarr format over h5? I'm just not overly familiar with it beyond knowing of its existence

**Review by ljgray — DISMISSED** [review]

**Comment by jrs65** [comment]
You can't do parallel IO on chunked HDF5 files. They claim you can, but in reality it crashes (you can see a long series of issues we've filed about it on their forums). Zarr does at least work for that use case.

**Comment by jrs65** [comment]
- [ ] Should change the delay spectrum setting to assume a complex time domain.

**Review by ljgray — APPROVED** [review]

**Pull request merged**
