### PR TITLE
Quarterstack updates

### PR DESCRIPTION
**Pull request by jrs65**
- feat(quarterstack): allow revisions to be judged by opinions from different revisions
- fix(quarterstack): update paths to new /project space
- feat(quarterstack): add extra RFI flagging and thresholding to processing
- refactor(quarterstack): miscellaneous cleanups

### CODE REVIEW

**Comment by ssiegelx** [comment]
If you want to flag the narrowband gain errors, that can be done by adding this to the config file:
```
    # Load gain errors as a function of time
    - type: ch_pipeline.core.io.LoadSetupFile
      out: gerr
      params:
        filename: "/project/rpp-chime/chime/chime_processed/gain/gain_errors/rev_00/20180905_20191231_gain_inverted_error_input_flagged.h5"
        distributed: Yes

    # Apply a mask that removes frequencies and times that suffer from gain errors
    - type: ch_pipeline.analysis.calibration.FlagNarrowbandGainError
      requires: gerr
      in: sstream
      out: mask_gerr
      params:
        transition: 600.0
        threshold: 1.0e-3
        ignore_input_flags: Yes
        save: Yes
        output_name: "gain_error_mask_{tag}.h5"

    - type: draco.analysis.flagging.ApplyRFIMask
      in: [sstream, mask_gerr]
      out: sstream_no_gerr
```
I will create a separate file for each year.  Right now there is 2018/2019 file and 2020 file available in that directory.

**Comment by jrs65** [comment]
Awesome. Thanks @ssiegelx !

**Comment by jrs65** [comment]
@ssiegelx is it a lot of work to generate the 2021 file? I think we have a bunch of obviously good data from the year we could use.

**Comment by ssiegelx** [comment]
No it's not much work.  I should have the file for 2021 ready tomorrow.

**Comment by jrs65** [comment]
I think this one is actually ready to review. It's what i'm using for the rev07 stacks.

**Review by ljgray — DISMISSED** [review]
These changes look good, but we'll have to address the failing test. It looks similar to radiocosmology/caput#245 and radiocosmology/caput#246

**Comment by jrs65** [comment]
@ljgray let's see if the tests on this one pass now.

**Comment by ljgray** [comment]
Seems to be working. Just requested a review from Seth due to the PR rules we added a couple months ago

**Review by ssiegelx — APPROVED** [review]
The gain error file for 2021 can be updated now if you are plan to stack those days.  Otherwise looks good.

**Comment by ljgray** [comment]
@ssiegelx I've updated the 2021 gain error file path and rebased to master, so I think this should be ok to merge now

**Review by ssiegelx — APPROVED** [review]

**Pull request merged**
