### PR TITLE
Pull HFB staging into master

### PR DESCRIPTION
**Pull request by jrs65**

### CODE REVIEW

**Review by rikvl — APPROVED** [review]
I resolved the merge conflicts. Apart from one, they seemed more like hiccups where I thought they should have merged automatically. Either way, I think this is now ready to be merged.

**Comment by rikvl** [comment]
I thought this should be a "rebase and merge" to keep some of the HFB commit history intact, but now GitHub tells me "This branch cannot be rebased due to conflicts". @jrs65, did you want to "squash and merge" or should we rebase `hfb-staging` onto `master`?

**Comment by jrs65** [comment]
I don't think we want to squash and merge as we'll lose all the history. I think the best thing to do is for me to force a normal merge (ignoring the linear history requirement).

**Comment by rikvl** [comment]
Ah, if that's an option, that would be preferable in this case. For me GitHub says that "create a merge commit" is "not enabled for this branch". Do you have privileges to force it? If so, go ahead!

**Pull request merged**
