### PR TITLE
Solar Analysis Code

### PR DESCRIPTION
**Pull request by wulfda02**
This includes two main updates. 

1. It includes updates to `analysis.solar.SolarCalibration` and `analysis.solar.SolarClean` which this branch inherited from previous solar analysis branches (I believe by Seth), which have never been merged into master.  I didn't write or use these pieces of code, but I thought they might be merged for the sake of posterity.  If others prefer, I'm ok with dropping these changes.
2. It includes updates to `analysis.solar.SunClean` and the addition of `analysis.solar.SunCalibration` which was used in for the solar beam analysis.

### CODE REVIEW

**Comment by jrs65** [comment]
Oh dear. I seem to have dropped the ball with this and was apparently meant to review it a year ago. Eeek. Sorry! I guess when the merge conflicts are all sorted out we can look at getting that done again.

**Comment by wulfda02** [comment]
No worries.  I'm working on rebasing it now, and I'll also update the function names to something more self-explanitory.  I'll ping you and Seth when I think it's ready

**Comment by wulfda02** [comment]
OK, @ssiegelx and @jrs65, this is ready for your review.  Please let me know if you'd like any other changes

**Comment by wulfda02** [comment]
Yeah, I think that sounds like a good plan.  I don't understand all the changed files.  I did try rebasing the branch so that wouldn't be an issue, but in the end it's probably easy to make a new branch as you suggest.  I'll do that an make a new PR

**Comment by wulfda02** [comment]
Ok, I've done that.  The new pull request is #135

**Pull request closed without merging**
