### PR TITLE
feat(init): add lazy versioning

### PR DESCRIPTION
**Pull request by ljgray**
Basic implementation from [StackOverflow](https://stackoverflow.com/a/52359211/18850844) (as found by @jrs65)

Seems to work fine with some basic experimentation but should be tested a bit more.

### CODE REVIEW

**Comment by ljgray** [comment]
Todo: test run pipeline with these changes

**Comment by ljgray** [comment]
Interestingly, this doesn't seem to speed up chp calls much. The top-level module import `import ch_pipeline` happens much faster, but `from ch_pipeline.processing import client` runs very slowly, even with lazy version handling added to all modules imported by `client`.

**Comment by jrs65** [comment]
> Interestingly, this doesn't seem to speed up chp calls much. The top-level module import `import ch_pipeline` happens much faster, but `from ch_pipeline.processing import client` runs very slowly, even with lazy version handling added to all modules imported by `client`. Obviously importing `client` is importing several other modules, whereas the only time spent when importing `ch_pipeline` was in `versioneer`. Something else is likely causing the slow `chp` startup time.

I wonder what else it's doing. Can you pass it run it via `python -m cProfile` and see what it's doing?

**Comment by ljgray** [comment]
> I wonder what else it's doing. Can you pass it run it via `python -m cProfile` and see what it's doing?

prfl5.prof in my scratch space. Seems like a ton of importlib calls. I haven't dug into it much more than that yet. Each relevant import (caput, chimdb.core, etc...) has a lazy_version branch.

**Comment by ljgray** [comment]
Proposing to close and reject this PR as I don't think it adds anything of value, at least as far as I can tell.

**Comment by ljgray** [comment]
Final comment - profiled the same import on my own machine. Total time ~0.37 secs. Number of calls is comparable to running on cedar, total time is just way faster.

**Pull request closed without merging**
